### ISSUE TITLE
Horizontal Scroll Bar

### ISSUE THREAD

**Issue by alekskivuls** [BeachHacks/beachhacks.github.io#11]
Unnecessary horizontal scroll bar is present when viewing site.

**Comment by jaylenw** [comment]
Looks like multiple people with bootstrap has this problem.

Will attempt to fix. Will try this...

body{
       overflow-x: hidden;
}


@alekskivuls @mbotsko7 @anthonyprograms

**Comment by jaylenw** [comment]
Horizontal bar issue fixed. Changes below.
f963d3fd97b8a87fc9b7269c8f01687e5675d6a6
