### ISSUE TITLE
add sponsors div(s)

### ISSUE THREAD

**Issue by jaylenw** [BeachHacks/beachhacks.github.io#19]
add sponsors when needed.

First need to add ASI ACM and MLH logos.

Then other sponsors that come on board.

@alekskivuls @mbotsko7 @anthonyprograms

**Comment by anthonyprograms** [comment]
How are we laying this out? Not sure what the type of sponsorships are but we would have the largest sponsorship at 1 column, every n level beneath that would be n columns? So biggest (being level 1) sponsorship at has 1 column, level 2 has 2 columns and so on?

**Comment by anthonyprograms** [comment]
What are the levels of sponsorship? Platinum? Gold? Silver? Bronze?

**Comment by anthonyprograms** [comment]
I'm temporarily going with the levels of sponsorship I mentioned above ^^. I've created a new branch (sponsor-div) and already pushed to it.

**Comment by mbotsko7** [comment]
The BeachHacks sponsor levels will be Diamond, Gold, Silver, and Bronze. I've added you to the Drive for BeachHacks, review the minutes section for any details you missed.

**Comment by anthonyprograms** [comment]
Alright, thanks.

**Comment by mbotsko7** [comment]
Heads up, MLH has a rule now that they can't be listed as a sponsor, only as a partner. So we need to add them, ASI, and ACM to another div called University Partners. University Partners are all equal to each other and would be listed after the Bronze tier (it's been discussed in meetings, sorry I forgot to remind you Anthony)

**Comment by anthonyprograms** [comment]
It's fine, I'll make the edit soon.

**Comment by anthonyprograms** [comment]
Just added in the university partners

**Comment by alekskivuls** [comment]
a6e6403115525459d3c78436ce6bc317c805879d
