### ISSUE TITLE
Insert Final Image

### ISSUE THREAD

**Issue by mbotsko7** [BeachHacks/beachhacks.github.io#33]
Cherie has provided the logo to overlay the triangle gradient, so let's shrink the final image and overlay the two of them and then we can make registration public
@jaylenw @alekskivuls @anthonyprograms

**Comment by mbotsko7** [comment]
Just branched my version of the final image...didn't shrink the image yet

**Comment by alekskivuls** [comment]
Now the button doesn't match the style of the logo. The font is also still hard to read cause it's too thin. Do we have a thicker version of the logo? Last it's crammed in there and needs some padding.

**Comment by mbotsko7** [comment]
Cherie's logo is based on Roboto Thin as I understand it. The rest of the website is running on Roboto regular.
