### ISSUE TITLE
Firefox problem with banner when on small resolutions

### ISSUE THREAD

**Issue by jaylenw** [BeachHacks/beachhacks.github.io#36]
@alekskivuls @cheriejw @mbotsko7 @anthonyprograms thoughts?
This can be replicated also on firefox desktop browser
# Below is the Firefox view where banner not showing properly...

![screenshot_20160222-032616](https://cloud.githubusercontent.com/assets/6505395/13217010/6a3e6194-d914-11e5-8d6a-0373c3841994.png)
# yet on chrome mobile the banner is fine.

![screenshot_20160222-032633](https://cloud.githubusercontent.com/assets/6505395/13217034/94e64db2-d914-11e5-9e62-c066f106d93d.png)

**Comment by alekskivuls** [comment]
No longer using this banner.
