### ISSUE TITLE
New Logos

### ISSUE THREAD

**Issue by mbotsko7** [BeachHacks/beachhacks.github.io#37]
Amazon Student
BeachCon
CECS
UltraPress
@jaylenw 
@alekskivuls 
@anthonyprograms

**Comment by anthonyprograms** [comment]
I got the logos up, BeachCon is the only one that is a SVG though. I will get the other 3 converted, I was having some issues with them showing up but I'll get them fixed and uploaded asap.

**Comment by jaylenw** [comment]
thanks anthony for taking the initiative on getting this done
