### ISSUE TITLE
Logo spills over on text

### ISSUE THREAD

**Issue by jaylenw** [BeachHacks/beachhacks.github.io#40]
On lower resolution screens, the logo gets pushed down and overflows on the next div

![screenshot from 2017-02-02 22-57-43](https://cloud.githubusercontent.com/assets/6505395/22582337/28df7556-e99b-11e6-9d8b-90a9443305b3.png)

**Comment by alekskivuls** [comment]
Fixed in e3fb68700900e77cca159dfdc5a5aa8f9add015c
