### ISSUE TITLE
Navigation tab links text vanishes

### ISSUE THREAD

**Issue by jaylenw** [BeachHacks/beachhacks.github.io#48]
Clicking on a link in the navigation tab and retain mouse hover over the link results in the text bleeding into the background tab color.

![screenshot from 2017-02-13 01-33-45](https://cloud.githubusercontent.com/assets/6505395/22877929/86d74e38-f18c-11e6-923e-22639f852bc8.png)

**Comment by RichCherng** [comment]
@alekskivuls might've found the root cause of this bug. This caused by page-scroll class and the javascript for scrolling in grayscale.js.

**Comment by jaylenw** [comment]
@RichCherng , @alekskivuls , @hongvt Verified this is no longer a problem. As of commit commit 73d5fdef9c4c41b20a8efcf0753705ef983edc45 that i checked, its all good.
